// A block that applies various Gradle plugins to enable specific build features.
plugins {
    // Applies the standard plugin for building an Android application.
    id("com.android.application")
    // Enables Kotlin language support for Android development.
    id("org.jetbrains.kotlin.android")
    // Applies the Hilt plugin for dependency injection.
    id("com.google.dagger.hilt.android")
    // Applies the KSP plugin for Kotlin annotation processing (used by Hilt and Room).
    id("com.google.devtools.ksp")
    // Applies the Google Services plugin to integrate with Firebase.
    id("com.google.gms.google-services")
}

// The main configuration block for all Android-specific build settings.
android {
    // Sets the unique package name for the application.
    namespace = "com.example.careconnect"
    // Specifies the Android API level the project is compiled against.
    compileSdk = 34

    // Default settings that apply to all build variants.
    defaultConfig {
        // Sets the unique identifier for the app on the Play Store.
        applicationId = "com.example.careconnect"
        // Sets the minimum Android API level required to run the app.
        minSdk = 24
        // Sets the target Android API level for which the app is designed.
        targetSdk = 34
        // An internal version number for the app.
        versionCode = 1
        // The user-facing version name for the app.
        versionName = "1.0"
        // Specifies the test runner class for instrumentation tests.
        testInstrumentationRunner = "androidx.test.runner.AndroidJUnitRunner"
        // Enables support for vector drawables on older Android versions.
        vectorDrawables {
            useSupportLibrary = true
        }
    }

    // Configuration for different build types, like 'debug' and 'release'.
    buildTypes {
        // Defines the settings for the production-ready release build.
        release {
            // Disables code shrinking and obfuscation for the release build.
            isMinifyEnabled = false
            // Specifies the ProGuard rules files for code optimization.
            proguardFiles(
                getDefaultProguardFile("proguard-android-optimize.txt"),
                "proguard-rules.pro"
            )
        }
    }

    // Sets the Java version compatibility for the project.
    compileOptions {
        // Specifies that the source code uses Java 8 language features.
        sourceCompatibility = JavaVersion.VERSION_1_8
        // Specifies that the generated bytecode is compatible with Java 8.
        targetCompatibility = JavaVersion.VERSION_1_8
        // Enables support for newer Java APIs on older Android versions.
        isCoreLibraryDesugaringEnabled = true
    }

    // Configures options specifically for the Kotlin compiler.
    kotlinOptions {
        // Sets the target JVM version for the generated Kotlin bytecode.
        jvmTarget = "1.8"
    }

    // A block to enable or disable specific features of the build process.
    buildFeatures {
        // Enables Jetpack Compose support for the project.
        compose = true
        // Enables the automatic generation of the BuildConfig.kt file.
        buildConfig = true
    }

    // Configures options for the Jetpack Compose compiler plugin.
    composeOptions {
        // Sets the version of the Kotlin compiler extension used by Compose.
        kotlinCompilerExtensionVersion = "1.5.13"
    }

    // Configures how app packaging (creating the APK/AAB) is handled.
    packaging {
        // Specifies rules for handling resource files during packaging.
        resources {
            // Excludes specific metadata files to prevent build conflicts.
            excludes += "/META-INF/{AL2.0,LGPL2.1}"
        }
    }
}

// A block that declares all the external libraries the app depends on.
dependencies {

    // Dependencies for core AndroidX functionality and UI components.
    // AndroidX Core & UI
    implementation("androidx.core:core-ktx:1.13.1")
    implementation("androidx.appcompat:appcompat:1.6.1")
    implementation("com.google.android.material:material:1.12.0")
    implementation("androidx.lifecycle:lifecycle-runtime-ktx:2.8.0")
    implementation("androidx.activity:activity-compose:1.9.0")

    // Dependencies for Jetpack Compose, managed by a Bill of Materials (BoM).
    // Jetpack Compose Bill of Materials (BoM)
    implementation(platform("androidx.compose:compose-bom:2024.05.00"))
    implementation("androidx.compose.ui:ui")
    implementation("androidx.compose.ui:ui-graphics")
    implementation("androidx.compose.ui:ui-tooling-preview")
    implementation("androidx.compose.material3:material3")
    implementation("androidx.compose.material:material-icons-extended")

    // The dependency for Jetpack Compose Navigation.
    // Navigation
    implementation("androidx.navigation:navigation-compose:2.7.7")

    // Dependencies for Hilt, used for dependency injection.
    // Hilt (Dependency Injection)
    implementation("com.google.dagger:hilt-android:2.51.1")
    ksp("com.google.dagger:hilt-compiler:2.51.1")
    implementation("androidx.hilt:hilt-navigation-compose:1.2.0")

    // Dependencies for Room, used for the local on-device database.
    // Room (Local Database)
    implementation("androidx.room:room-runtime:2.6.1")
    implementation("androidx.room:room-ktx:2.6.1")
    ksp("androidx.room:room-compiler:2.6.1")

    // Dependencies for Firebase, managed by a Bill of Materials (BoM).
    // Firebase Bill of Materials (BoM)
    implementation(platform("com.google.firebase:firebase-bom:33.0.0"))
    implementation("com.google.firebase:firebase-auth-ktx")
    implementation("com.google.firebase:firebase-firestore-ktx")
    implementation("com.google.firebase:firebase-analytics-ktx")

    // Dependencies for Kotlin Coroutines, used for asynchronous programming.
    // Coroutines
    implementation("org.jetbrains.kotlinx:kotlinx-coroutines-core:1.7.3")
    implementation("org.jetbrains.kotlinx:kotlinx-coroutines-android:1.7.3")
    implementation("org.jetbrains.kotlinx:kotlinx-coroutines-play-services:1.7.3")

    // The dependency for the interactive calendar library.
    implementation("io.github.boguszpawlowski.composecalendar:composecalendar:1.4.0")
    // The required dependency to enable newer Java APIs on older Android versions.
    coreLibraryDesugaring("com.android.tools:desugar_jdk_libs:2.0.4")


    // Dependencies used exclusively for running tests.
    // Testing
    testImplementation("junit:junit:4.13.2")
    androidTestImplementation("androidx.test.ext:junit:1.1.5")
    androidTestImplementation("androidx.test.espresso:espresso-core:3.5.1")
    androidTestImplementation(platform("androidx.compose:compose-bom:2024.05.00"))
    androidTestImplementation("androidx.compose.ui:ui-test-junit4")
    debugImplementation("androidx.compose.ui:ui-tooling")
    debugImplementation("androidx.compose.ui:ui-test-manifest")
}

