// Defines the file's location within the ViewModel architecture of the app.
package com.example.careconnect.ui.viewmodel

// Imports necessary libraries for ViewModel creation, state management, and the data layer.
import android.util.Log
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.setValue
import androidx.lifecycle.ViewModel
import androidx.lifecycle.viewModelScope
import com.example.careconnect.data.model.User
import com.example.careconnect.data.repository.CareRepository
import com.google.firebase.auth.FirebaseAuth
// Imports the Kotlin extension functions for Firebase services.
import com.google.firebase.auth.ktx.auth
import com.google.firebase.firestore.ktx.firestore
import com.google.firebase.ktx.Firebase
import dagger.hilt.android.lifecycle.HiltViewModel
import kotlinx.coroutines.launch
import kotlinx.coroutines.tasks.await
import javax.inject.Inject

// Defines the data structure for the authentication screen's UI state.
data class AuthState(
    val isLoading: Boolean = false,
    val error: String? = null
)

// Marks this class as a ViewModel that can be injected by Hilt.
@HiltViewModel
// Defines the ViewModel for authentication, injecting the data repository.
class AuthViewModel @Inject constructor(private val repository: CareRepository) : ViewModel() {
    // A public state variable that the UI can observe for changes.
    var authState by mutableStateOf(AuthState())
        // Restricts setting this state to only within the ViewModel.
        private set

    // A private property to get a convenient reference to the Firebase Auth instance.
    private val auth: FirebaseAuth = Firebase.auth

    // This function handles the logic for logging in a user.
    fun login(email: String, pass: String, onLoginSuccess: () -> Unit) {
        // Performs basic validation to ensure input fields are not empty.
        if (email.isBlank() || pass.isBlank()) {
            authState = authState.copy(error = "Email and password cannot be empty.")
            return
        }
        // Launches a coroutine to perform the network request off the main thread.
        viewModelScope.launch {
            // Updates the UI state to show a loading indicator.
            authState = AuthState(isLoading = true)
            // A try-catch block to handle potential network or authentication errors.
            try {
                // Calls the Firebase SDK to sign the user in and waits for the result.
                auth.signInWithEmailAndPassword(email, pass).await()
                // Updates the state to stop loading and triggers the success callback.
                authState = AuthState(isLoading = false)
                onLoginSuccess()
                // Catches any exceptions and updates the state with an error message.
            } catch (e: Exception) {
                authState = AuthState(isLoading = false, error = e.message ?: "Login failed.")
            }
        }
    }

    // This function handles the logic for registering a new user.
    fun register(name: String, email: String, pass: String, onRegistrationSuccess: () -> Unit) {
        // Performs basic validation to ensure all input fields are filled.
        if (name.isBlank() || email.isBlank() || pass.isBlank()) {
            authState = authState.copy(error = "All fields are required.")
            return
        }
        // Launches a coroutine to perform the registration process.
        viewModelScope.launch {
            // Updates the UI state to show a loading indicator.
            authState = AuthState(isLoading = true)
            // A try-catch block to handle potential errors during registration.
            try {
                // Creates the new user in Firebase Authentication.
                val authResult = auth.createUserWithEmailAndPassword(email, pass).await()
                // Retrieves the unique user ID generated by Firebase.
                val userId = authResult.user?.uid

                // Proceeds only if a valid user ID was successfully created.
                if (userId != null) {
                    // Creates a new User data object with the registration details.
                    val userProfile = User(
                        uid = userId,
                        name = name,
                        email = email,
                        role = "Primary Caregiver",
                        careCircleId = "SHARED_CARE_CIRCLE_ID_12345",
                        phone = "",
                        address = ""
                    )

                    // Saves the new user's profile data to a "users" collection in Firestore.
                    Firebase.firestore.collection("users").document(userId).set(userProfile).await()
                    // Updates the state to stop loading and triggers the success callback.
                    authState = AuthState(isLoading = false)
                    onRegistrationSuccess()
                    // Throws an exception if for some reason the user ID is null.
                } else {
                    throw Exception("Failed to get user ID.")
                }
                // Catches any exceptions and updates the state with an error message.
            } catch (e: Exception) {
                authState = AuthState(isLoading = false, error = e.message ?: "Registration failed.")
            }
        }
    }

    // A public function for the UI to call to clear any existing error messages.
    fun clearError() {
        authState = authState.copy(error = null)
    }
}

